server:
  port: 59100

spring:

  r2dbc:
    url: r2dbc:postgresql://localhost:${CROWDQ_DB_PORT}/${CROWDQ_DB_NAME}

  sql:
    init:
      mode: always
      platform: postgres

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
