spring:
  application:
    name: "CrowdQ User Service"
  profiles:
    active: "local"
  r2dbc:
    username: ${CROWDQ_DB_USER}
    password: ${CROWDQ_DB_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  prometheus:
    metrics:
      export:
        enabled: true

app:
  version: "@project.version@"
