spring:

  r2dbc:
    url: r2dbc:postgresql://crowdq-postgres:${CROWDQ_DB_PORT}/${CROWDQ_DB_NAME}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth-service:8443/realms/crowdq

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
