openapi: 3.0.4
info:
  title: CrowdQ User Service API
  version: 0.0.1-SNAPSHOT
  description: |-
    This is a multi-line description of the CrowdQ User Service API.
  contact:
    email: pedraza.miguez@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:59100
    description: Local server

tags:
  - name: user
    description: Operations related to users

paths:
  /users/{username}:
    get:
      tags:
        - user
      summary: Get user by username
      description: Returns a user based on their username.
      operationId: getUserByUsername
      parameters:
        - name: username
          in: path
          required: true
          description: The username of the user to retrieve
          schema:
            type: string
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
        '500':
          description: Internal server error

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "f234567e-89bc-1234-de56-78901234abcd"
        username:
          type: string
          example: "andrespmi"
        email:
          type: string
          format: email
          example: "andres@example.com"
        fullName:
          type: string
          example: "Andrés Pedraza"

  securitySchemes:
    KeycloakPassword:
      type: oauth2
      flows:
        password:
          tokenUrl: https://cantalobos.isasecret.com/realms/crowdq/protocol/openid-connect/token
          scopes:
            profile: Access your profile information
            email: Access your email address

security:
  - KeycloakPassword:
      - profile
      - email
